version: '2'

services:
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: pokelink

  pokelink_back:
    build: ./back
    ports: 
      - 3000:3000
    links:
      - mongo
    volumes:
      - ./back:/pokelink_back
    environment:
      NODE_ENV: prod
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: pokelink
      AUTH_SECRET: randomsecretpassword

  pokelink_front:
    build: ./front
    ports: 
      - 80:80